### ISSUE TITLE
API is showing "valid_mx": false

### ISSUE THREAD

**Issue by keigel2001** [sublime-security/emailrep.io#2]
I just checked multiple self-hosted emailaddresses. All of these show `"valid_mx": false`, but I don't understand why.

https://emailrep.io/keigel2001@keigel2001.net
```
curl emailrep.io/keigel2001@keigel2001.net
{
    "email": "keigel2001@keigel2001.net",
    "reputation": "low",
    "suspicious": true,
    "references": 2,
    "details": {
        "blacklisted": false,
        "malicious_activity": false,
        "malicious_activity_recent": false,
        "credentials_leaked": false,
        "credentials_leaked_recent": false,
        "data_breach": false,
        "last_seen": "never",
        "domain_exists": true,
        "domain_reputation": "low",
        "new_domain": false,
        "days_since_domain_creation": 773,
        "suspicious_tld": false,
        "spam": false,
        "free_provider": false,
        "disposable": false,
        "deliverable": false,
        "accept_all": false,
        "valid_mx": false,
        "spoofable": false,
        "spf_strict": true,
        "dmarc_enforced": true,
        "profiles": [
            "spotify",
            "twitter"
        ]
    }
}
```

The Domain is using DNSSEC with RSASHA256, properly configured (see https://dnssec-debugger.verisignlabs.com/keigel2001.net or http://dnsviz.net/d/keigel2001.net/dnssec/)
But also other domains without DNSSEC have the same problem.

A check at mxtoolbox said everything is ok.

Querying google-dns:
```
dig keigel2001.net MX +short @8.8.8.8
10 megan.keigel2001.net.
20 zooey.keigel2001.net.
```
Same output for cloudflare-dns and every nameserver delegated to the domain.

**Comment by jkamdjou** [comment]
Confirmed bug. Looking into it.

**Comment by jkamdjou** [comment]
This should now be fixed. It was due to a timeout on SMTP deliverability checks causing `valid_mx` to erroneously be set to `False`. Feel free to re-open the issue if you encounter any more problems.
