### ISSUE TITLE
API only behaves correctly when UA string contains "curl"

### ISSUE THREAD

**Issue by IISResetMe** [sublime-security/emailrep.io#3]
In Windows PowerShell, `curl` is an alias for the `Invoke-WebRequest` cmdlet, so when you execute:

    Invoke-WebRequest https://emailrep.io/bill@microsoft.com

... you get the full html of the web page in the response body. Changing the UserAgent string to anything with the substring `curl` makes it return the raw JSON:

    Invoke-WebRequest https://emailrep.io/bill@microsoft.com -UserAgent not_curl |ConvertFrom-Json
    # Works as expected

This is probably by design, but please consider either adding an optional query param (`?api=1` or whatever) to specify that output should be pure JSON, or at least document in the README that the user is expected to supply a user string containing `curl` :)

**Comment by jkamdjou** [comment]
This is now fixed for Windows PowerShell requests, so the raw JSON response will be returned. I'll make a note in the documentation to explain this behavior, which is intended to return the full web page for User Agents containing `Mozilla` (web browsers) and the raw JSON for all others.

**Comment by jkamdjou** [comment]
You can now also force a JSON response using the "Accept: application/json" HTTP header.

**Comment by IISResetMe** [comment]
Awesome, thanks for the prompt response and followup @jkamdjou!
