### ISSUE TITLE
How to pass API key in nodejs

### ISSUE THREAD

**Issue by heaversm** [sublime-security/emailrep.io#6]
Hi - trying to pass my API Key to deal with rate limiting issue and it doesn't seem to be having any effect (tried with a brand new API key and still got the rate limiting msg).

Following your nodejs code sample [in the docs](https://docs.sublimesecurity.com/reference/get_-email), here's what I'm trying:

```
const sdk = require("api")("@sublimesecurity/v0.3#49y4gl02wflaz");
sdk.server("https://emailrep.io");

sdk
  .auth(MY_API_KEY) //doesn't seem to change rate limiting, is this working?
  .get(`/${email}`)
```

**Comment by jkamdjou** [comment]
Hi @heaversm! To be honest, that is automatically generated code by our documentation system and may not be right. To use your API key, set it in the `Key` HTTP header:

https://docs.sublimesecurity.com/docs/emailrep-api#specify-your-api-key-in-the-key-header-field

Let me know if that works for you!

**Comment by heaversm** [comment]
---

**Comment by heaversm** [comment]
I followed up with the npm `api` module folks directly on this to see if the issue was on my usage of that module, and they [provided this response](https://github.com/readmeio/api/issues/433):

<img width="898" alt="Screen Shot 2022-04-19 at 12 51 18 PM" src="https://user-images.githubusercontent.com/520541/164084964-c58e313a-430f-4997-9967-ed45ce12e6aa.png">

Apparently there is no way to use the api module to interact with the emailrep API until that spec is updated.

I was able to get this to work with Axios in node though:

```
axios
    .get(`https://emailrep.io/${email}`, {
      headers: {
        Key: API_KEY,
        "User-Agent": "[ANY_STRING]",
      },
    })
    .then((response) => {
      console.log("success", response.data);
      res.json(response.data);
    })
    .catch((err) => {
      console.error(err);
      res.json({
        error: `there was an error with your reputation request: ${err.statusText}`,
        details: err.statusText,
      });
    });
```

**Comment by scottydev** [comment]
@heaversm was pulling my hair out over the same issue. [Foursquare's API docs](https://developer.foursquare.com/reference/place-details) recommend to use the API package for Node as well but was always getting header authorization problems. Once I switched to Axios all was well again.

Thanks for the call out. Hoping the API team can sort the Node header auth issues out.
